import { Header } from '@/layouts';
import ThemeProviderWrapper from '@/theme/theme-provider';
import { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import RootStyleRegistry from './emotion';
import FirstLoading from './first-loading';

import 'swiper/css';
import 'swiper/css/autoplay';
import 'swiper/css/bundle';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import './globals.css';
import Footer from './footer';

const inter = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bossen',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/logo.svg',
      type: 'image/svg',
    },
    shortcut: { url: '/logo.svg', type: 'image/svg' },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootStyleRegistry>
          <ThemeProviderWrapper>
            <Header />
            <FirstLoading />
            <main>{children}</main>
            <Footer />
          </ThemeProviderWrapper>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
